apiVersion: v1
kind: Pod

metadata:
  name: banking-app

spec:
  containers:
    - name: banking-app
      image: banking_app-app:latest
      imagePullPolicy: Never

      ports:
        - containerPort: 5000
