apiVersion: apps/v1
kind: Deployment

metadata:
  name: banking-app
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: banking-app

  template:
    metadata:
      labels:
        app: banking-app

    spec:
      containers:
        - name: banking-app
          image: banking-app:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE

            - name: FLASK_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_SECRET_KEY

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
