apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: banking

data:
  DB_HOST: mysql
  DB_PORT: "3306"
  MYSQL_DATABASE: banking_db
  FLASK_SECRET_KEY: simplebank_super_secret_key_2024
